server:
  port: 8082
#DB Configuration
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.142.174:3306/public_data
    username: data
    password: keNDzJHejiXY5n3T
  redis:
    host: 39.108.142.174
    port: 6379
    password: avc123
    timeout: 6000
    jedis:
      pool:
        max-active: 100
        max-idle: 16
        max-wait: 1000ms
        min-idle: 8
    output:
      ansi:
        enabled: detect

mybatis-plus:
  type-aliases-package: com.example.model

  mapper-locations: classpath:mapping/*.xml

  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging
logging:
  level:
    com.xc.springboot: debug
encrypt-type: # 0：普通， 1：国密
  encrypt-type: 0

group-channel-connections-config:
  caCert: ca.crt
  sslCert: sdk.crt
  sslKey: sdk.key
  all-channel-connections:
    - group-id: 1 #group ID
      connections-str:
        # 若节点小于v2.3.0版本，查看配置项listen_ip:channel_listen_port
        - 47.106.112.206:20200 # node channel_listen_ip:channel_listen_port
        - 47.106.112.206:20201
    - group-id: 2
      connections-str:
        # 若节点小于v2.3.0版本，查看配置项listen_ip:channel_listen_port
        - 47.106.112.206:20202 # node channel_listen_ip:channel_listen_port
        - 47.106.112.206:20203
channel-service:
  group-id: 1 # sdk实际连接的群组
  agency-name: fisco # 机构名称
debug: true